name: Build Z3 Static

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make g++

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build Z3
        shell: bash
        run: bash scripts/build.sh

      - name: Archive build output
        shell: bash
        run: |
          mkdir -p archives
          zip -r "archives/z3-${{ runner.os }}.zip" dist

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: archives/z3-${{ runner.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
